site_name: Sitekick Remastered
repo_url: https://github.com/SitekickRemastered/Art
repo_name: SitekickRemastered/Art
site_url: https://docs.sitekickremastered.com/
dev_addr: '0.0.0.0:8014'
docs_dir: docs
nav:
  - Home: index.md
  - Download: /download/
  - Blog: /blog/
  - Docs: /docs/
  - Changelog: /changelog/
  - Discord: http://discord.sitekickremastered.com/
  - Status: https://status.sitekickremastered.com/status/site
theme:
  icon:
    repo: fontawesome/brands/github
#  logo: /images/misc/logo.png
  favicon: /images/ico/favicon.ico
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotation
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Custom Homepage Elements
home_cover_image: images/misc/appicon.png
home_tagline: Sitekick Remastered Beta
home_description: |
  Produced by fans, for fans. Sitekick Remastered is a completely free game, containing no advertisements, subscriptions, microtransactions, or any other form of monetization.

# Gradient Color
home_gradient_hsla: hsla(53, 87%, 51%,1)

# Custom Homepage Button(s)
home_button1_name: Play now
home_button1_url: /download/
home_button1_theme: md-button md-button--primary
home_button1_icon: 
home_button1_blurb: |
  Sitekick Remastered is available for Android, Windows, and Xbox.

home_button2_name: Join us on Discord
home_button2_url: https://discord.sitekickremastered.com/
home_button2_theme: md-button md-button--primary
home_button2_icon: 
home_button2_blurb: |
  Chat and Trade with over 900 other players on our official Discord server.


# Homepage Code Execution
#home_execute_js: | # Javascript to execute when accessing the homepage
#  console.log("This is an example!");

plugins:
  - blog
  - tags:
      tags_file: tags.md 
  - search

extra:
  #generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.sitekickremastered.com
    - icon: fontawesome/brands/github
      link: https://github.com/SitekickRemastered/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sitekickremastered/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SitekickGame
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZQ0gBa3SbxwfQ5zp4029PQ
  tags:
    tag: identifier